name: docker

on: [push, pull_request]

jobs:
  build:
    name: Build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: oouxx/proxyaggre:latest
          secrets:
            - GITHUB_AUTH_TOKEN=${{github.token}}

      - name: Image digest
        run: echo ${{steps.docker_build.outputs.digest}}
